//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stonks.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle WindowBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["WindowBounds"]));
            }
            set {
                this["WindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62,204,74,75,57,93,55,82,55,82,74,75")]
        public string ColumnWidths {
            get {
                return ((string)(this["ColumnWidths"]));
            }
            set {
                this["ColumnWidths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EncryptedApiKey {
            get {
                return ((string)(this["EncryptedApiKey"]));
            }
            set {
                this["EncryptedApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogDirectory {
            get {
                return ((string)(this["LogDirectory"]));
            }
            set {
                this["LogDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerboseLogging {
            get {
                return ((bool)(this["VerboseLogging"]));
            }
            set {
                this["VerboseLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal PollingInterval {
            get {
                return ((decimal)(this["PollingInterval"]));
            }
            set {
                this["PollingInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<ArrayOfStockDefinition>
  <StockDefinition>
    <Symbol>AAPL</Symbol>
    <Shares>0</Shares>
    <PricePaid>0.00</PricePaid>
    <Notes>Sample-01</Notes>
    <Chart>true</Chart>
  </StockDefinition>
  <StockDefinition>
    <Symbol>AMD</Symbol>
    <Shares>100.00</Shares>
    <PricePaid>200</PricePaid>
    <Notes>Sample-02</Notes>
    <Chart>true</Chart>
  </StockDefinition>
  <StockDefinition>
    <Symbol>INTC</Symbol>
    <Shares>0</Shares>
    <PricePaid>0</PricePaid>
    <Notes>Sample-03</Notes>
    <Chart>true</Chart>
  </StockDefinition>
  <StockDefinition>
    <Symbol>MSFT</Symbol>
    <Shares>100</Shares>
    <PricePaid>200</PricePaid>
    <Notes>Sample-04</Notes>
    <Chart>true</Chart>
  </StockDefinition>
  <StockDefinition>
    <Symbol>NVDA</Symbol>
    <Shares>100</Shares>
    <PricePaid>150</PricePaid>
    <Notes>Sample-05</Notes>
    <Chart>true</Chart>
  </StockDefinition>
  <StockDefinition>
    <Symbol>SPCX</Symbol>
    <Shares>100</Shares>
    <PricePaid>200</PricePaid>
    <Notes>Sample-06</Notes>
    <Chart>true</Chart>
  </StockDefinition>
  <StockDefinition>
    <Symbol>BTC/USD</Symbol>
    <Shares>0</Shares>
    <PricePaid>0</PricePaid>
    <Notes>Sample-07</Notes>
    <Chart>false</Chart>
  </StockDefinition>
</ArrayOfStockDefinition>")]
        public string StockDefinitions {
            get {
                return ((string)(this["StockDefinitions"]));
            }
            set {
                this["StockDefinitions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChartDirectory {
            get {
                return ((string)(this["ChartDirectory"]));
            }
            set {
                this["ChartDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayCharts {
            get {
                return ((bool)(this["DisplayCharts"]));
            }
            set {
                this["DisplayCharts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChartValues {
            get {
                return ((int)(this["ChartValues"]));
            }
            set {
                this["ChartValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LogType {
            get {
                return ((int)(this["LogType"]));
            }
            set {
                this["LogType"] = value;
            }
        }
    }
}
